# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "src/Migrator/EventFlow.Migrator.csproj"
RUN dotnet publish "src/Migrator/EventFlow.Migrator.csproj" --configuration Release --output /app/publish --no-restore /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Production DOTNET_EnableDiagnostics=0
COPY --from=build /app/publish .
USER $APP_UID
ENTRYPOINT ["dotnet", "EventFlow.Migrator.dll"]
