spring.application.name=eventflow-api

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8082

springdoc.swagger-ui.path=/swagger-ui

spring.security.user.name=admin
spring.security.user.password=1234
